version: "3.8"

services:
  app:
    build: ./chat-application-backend
    container_name: springboot-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/chatapp?authSource=admin
    depends_on:
      - mongo
      - frontend

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: chatapp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./chat-application-frontend
    container_name: react-app
    ports:
      - 5173:80

volumes:
  mongo_data:
